### ISSUE TITLE
There is app not detected in in-app icon request feature

### ISSUE THREAD

**Issue by fedry** [mirrorkeydev/Appstract#19]
Hi, I would like to request icon for com.ticktick.task app. It is not detected from in-app feature.

**Comment by mirrorkeydev** [comment]
Hi @fedry!

Thanks for opening an issue. Unfortunately, I didn't create the dashboard for this icon pack, so I'm not sure why the icon isn't being detected. I also can't add the icon to the top 1000 requested icons list because I have no idea how many people actually are requesting the icon, since as you've noted, it's not being detected by the app.

However!

I believe I've made icons for other todo-like apps; if you like, you could make an icon based on the existing icons (or make something completely from scratch!) and open a pull request to add the icon :) More details in the [contribution guide](https://github.com/mirrorkeydev/Appstract/blob/master/CONTRIBUTING.md).

I'm going to close this for now, but feel free to leave more comments or questions if you have any.
