### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by benstockil** [mirrorkeydev/Appstract#41]
Would it be possible to distribute the app via F-Droid? As someone who runs Android without Google Play Services, this would be really helpful.

**Comment by mirrorkeydev** [comment]
After a quick skim of the [Inclusion Policy](https://www.f-droid.org/en/docs/Inclusion_Policy/), I think Appstract might not meet the criteria to be distributed via F-Droid. Specifically:

> For software to be FLOSS, the software in its entirety must be so - including all libraries and dependencies used. Additionally, it must be buildable with only FLOSS tools.

> Every effort is made to verify that this is actually the case, both by visual inspection of the source, and **by building the application from the published source.**

This repository doesn't actually provide all the source for Appstract, since I'm mostly just using it to track public contributions to icon designs. I didn't build the [dashboard](https://github.com/zixpo/candybar), so you could use the sample CandyBar repo and piece together a working version from source, but it wouldn't quite match the actual build I push to Google Play. Additionally, I'm not sure if there are Play Service dependencies in the dashboard (billing library and license checker come to mind) which would break (?) on an Android distribution without those services.

One thing you could try is sideloading Appstract from one of those APK mirror websites. If it works out of the box, I could just start adding APKs to my releases on GitHub, and you're free to sideload those.

**Comment by benstockil** [comment]
I installed Appstract from Aurora Store; the icons work fine but I get an "Unable to check license" error message whenever I open the app.

**Comment by mirrorkeydev** [comment]
Oh awesome! Does that meet your needs or do you need the dashboard itself to work as well? It's just a preview of all the icons and some stats about the library.

**Comment by benstockil** [comment]
I don't really need the dashboard to use the icons, although some launchers don't provide a search function, so its sometimes easier to go to the app dashboard to pick an icon for an unsupported app.

If the dashboard doesn't require many features, would it be possible to create a custom dashboard for Appstract? I'd be happy to help when I get the time, but I don't have much experience with Java / Kotlin. I would love to see the icon pack make its way over to F-Droid.

**Comment by mirrorkeydev** [comment]
I have zero Android dev experience (hence using CandyBar dashboard), so I have to say that creating a custom dashboard from scratch would be a large endeavor for me. CandyBar does have a lot of neat features that would take a bit to recreate (icon request portal, icon search, icon tab groups, icon bookmark, in-app purchases, etc.). Maybe if there already existed an F-Droid-approved dashboard I could port to I would consider it, but for now a project involving creating a new dashboard is outside of the scope of effort I can put into maintaining this project :) I appreciate the interest in getting Appstract to new platforms though!

**Comment by benstockil** [comment]
I found [this issue](https://github.com/zixpo/candybar/issues/18) on the CandyBar repository which says that it's F-droid compatible if all billing/license-checking features are removed. I might fork the Arcticons repo (which has already stripped these features) and see if I can switch out the icons?

**Comment by mirrorkeydev** [comment]
Ah, only issue with that plan is that I haven't published all of Appstract's icons to this repo -- currently, it's only tracking public contributions, not the initial set that I created back in 2018-19. For various reasons, I don't see myself changing that in the near future, although if it really is as easy as forking Arcticons and swapping in the icons, I might consider adding that to my release schedule. Historically though, cutting new releases of Appstract has been a a bit of a pain -- there's updating the dashboard, importing new icons, generating new XML files, regenerating the top requested icons, reviewing and fixing public contributions that are broken in some or another, dealing with Kotlin warnings I only half understand, hand testing to make sure the latest build didn't break anything, and then updating two separate apps. All in all, each release takes well over 5 hours of my free time, so I hope it's clear why I'm a bit reluctant to add more to that plate.

**Comment by Donnnno** [comment]
Hi, Arcticons dev here and stumbled across this issue.

Just wanted to let you know that I've successfully removed all proprietary parts from Candybar, and made it as easy to implement as Candybar here:
https://github.com/Donnnno/candybar-foss
https://github.com/Donnnno/candybar-foss-sample
